countyNames = (
	( "0", "select a county" ),
	( "Abbeville County", "Abbeville County" ),
	( "Acadia Parish", "Acadia Parish" ),
	( "Accomack County", "Accomack County" ),
	( "Ada County", "Ada County" ),
	( "Adair County", "Adair County" ),
	( "Adams County", "Adams County" ),
	( "Addison County", "Addison County" ),
	( "Aiken County", "Aiken County" ),
	( "Aitkin County", "Aitkin County" ),
	( "Alachua County", "Alachua County" ),
	( "Alamance County", "Alamance County" ),
	( "Alameda County", "Alameda County" ),
	( "Alamosa County", "Alamosa County" ),
	( "Albany County", "Albany County" ),
	( "Albemarle County", "Albemarle County" ),
	( "Alcona County", "Alcona County" ),
	( "Alcorn County", "Alcorn County" ),
	( "Aleutians East Borough", "Aleutians East Borough" ),
	( "Aleutians West Census Area", "Aleutians West Census Area" ),
	( "Alexander County", "Alexander County" ),
	( "Alexandria city", "Alexandria city" ),
	( "Alfalfa County", "Alfalfa County" ),
	( "Alger County", "Alger County" ),
	( "Allamakee County", "Allamakee County" ),
	( "Allegan County", "Allegan County" ),
	( "Allegany County", "Allegany County" ),
	( "Alleghany County", "Alleghany County" ),
	( "Allegheny County", "Allegheny County" ),
	( "Allen County", "Allen County" ),
	( "Allen Parish", "Allen Parish" ),
	( "Allendale County", "Allendale County" ),
	( "Alpena County", "Alpena County" ),
	( "Amador County", "Amador County" ),
	( "Amelia County", "Amelia County" ),
	( "Amherst County", "Amherst County" ),
	( "Amite County", "Amite County" ),
	( "Anchorage Municipality", "Anchorage Municipality" ),
	( "Anderson County", "Anderson County" ),
	( "Andrew County", "Andrew County" ),
	( "Andrews County", "Andrews County" ),
	( "Androscoggin County", "Androscoggin County" ),
	( "Angelina County", "Angelina County" ),
	( "Anne Arundel County", "Anne Arundel County" ),
	( "Anoka County", "Anoka County" ),
	( "Anson County", "Anson County" ),
	( "Antelope County", "Antelope County" ),
	( "Antrim County", "Antrim County" ),
	( "Apache County", "Apache County" ),
	( "Appanoose County", "Appanoose County" ),
	( "Appling County", "Appling County" ),
	( "Appomattox County", "Appomattox County" ),
	( "Aransas County", "Aransas County" ),
	( "Arapahoe County", "Arapahoe County" ),
	( "Archer County", "Archer County" ),
	( "Archuleta County", "Archuleta County" ),
	( "Arenac County", "Arenac County" ),
	( "Arkansas County", "Arkansas County" ),
	( "Arlington County", "Arlington County" ),
	( "Armstrong County", "Armstrong County" ),
	( "Aroostook County", "Aroostook County" ),
	( "Arthur County", "Arthur County" ),
	( "Ascension Parish", "Ascension Parish" ),
	( "Ashe County", "Ashe County" ),
	( "Ashland County", "Ashland County" ),
	( "Ashley County", "Ashley County" ),
	( "Ashtabula County", "Ashtabula County" ),
	( "Asotin County", "Asotin County" ),
	( "Assumption Parish", "Assumption Parish" ),
	( "Atascosa County", "Atascosa County" ),
	( "Atchison County", "Atchison County" ),
	( "Athens County", "Athens County" ),
	( "Atkinson County", "Atkinson County" ),
	( "Atlantic County", "Atlantic County" ),
	( "Atoka County", "Atoka County" ),
	( "Attala County", "Attala County" ),
	( "Audrain County", "Audrain County" ),
	( "Audubon County", "Audubon County" ),
	( "Auglaize County", "Auglaize County" ),
	( "Augusta County", "Augusta County" ),
	( "Aurora County", "Aurora County" ),
	( "Austin County", "Austin County" ),
	( "Autauga County", "Autauga County" ),
	( "Avery County", "Avery County" ),
	( "Avoyelles Parish", "Avoyelles Parish" ),
	( "Baca County", "Baca County" ),
	( "Bacon County", "Bacon County" ),
	( "Bailey County", "Bailey County" ),
	( "Baker County", "Baker County" ),
	( "Baldwin County", "Baldwin County" ),
	( "Ballard County", "Ballard County" ),
	( "Baltimore County", "Baltimore County" ),
	( "Baltimore city", "Baltimore city" ),
	( "Bamberg County", "Bamberg County" ),
	( "Bandera County", "Bandera County" ),
	( "Banks County", "Banks County" ),
	( "Banner County", "Banner County" ),
	( "Bannock County", "Bannock County" ),
	( "Baraga County", "Baraga County" ),
	( "Barber County", "Barber County" ),
	( "Barbour County", "Barbour County" ),
	( "Barnes County", "Barnes County" ),
	( "Barnstable County", "Barnstable County" ),
	( "Barnwell County", "Barnwell County" ),
	( "Barren County", "Barren County" ),
	( "Barron County", "Barron County" ),
	( "Barrow County", "Barrow County" ),
	( "Barry County", "Barry County" ),
	( "Bartholomew County", "Bartholomew County" ),
	( "Barton County", "Barton County" ),
	( "Bartow County", "Bartow County" ),
	( "Bastrop County", "Bastrop County" ),
	( "Bates County", "Bates County" ),
	( "Bath County", "Bath County" ),
	( "Baxter County", "Baxter County" ),
	( "Bay County", "Bay County" ),
	( "Bayfield County", "Bayfield County" ),
	( "Baylor County", "Baylor County" ),
	( "Beadle County", "Beadle County" ),
	( "Bear Lake County", "Bear Lake County" ),
	( "Beaufort County", "Beaufort County" ),
	( "Beauregard Parish", "Beauregard Parish" ),
	( "Beaver County", "Beaver County" ),
	( "Beaverhead County", "Beaverhead County" ),
	( "Becker County", "Becker County" ),
	( "Beckham County", "Beckham County" ),
	( "Bedford County", "Bedford County" ),
	( "Bee County", "Bee County" ),
	( "Belknap County", "Belknap County" ),
	( "Bell County", "Bell County" ),
	( "Belmont County", "Belmont County" ),
	( "Beltrami County", "Beltrami County" ),
	( "Ben Hill County", "Ben Hill County" ),
	( "Benewah County", "Benewah County" ),
	( "Bennett County", "Bennett County" ),
	( "Bennington County", "Bennington County" ),
	( "Benson County", "Benson County" ),
	( "Bent County", "Bent County" ),
	( "Benton County", "Benton County" ),
	( "Benzie County", "Benzie County" ),
	( "Bergen County", "Bergen County" ),
	( "Berkeley County", "Berkeley County" ),
	( "Berks County", "Berks County" ),
	( "Berkshire County", "Berkshire County" ),
	( "Bernalillo County", "Bernalillo County" ),
	( "Berrien County", "Berrien County" ),
	( "Bertie County", "Bertie County" ),
	( "Bethel Census Area", "Bethel Census Area" ),
	( "Bexar County", "Bexar County" ),
	( "Bibb County", "Bibb County" ),
	( "Bienville Parish", "Bienville Parish" ),
	( "Big Horn County", "Big Horn County" ),
	( "Big Stone County", "Big Stone County" ),
	( "Billings County", "Billings County" ),
	( "Bingham County", "Bingham County" ),
	( "Black Hawk County", "Black Hawk County" ),
	( "Blackford County", "Blackford County" ),
	( "Bladen County", "Bladen County" ),
	( "Blaine County", "Blaine County" ),
	( "Blair County", "Blair County" ),
	( "Blanco County", "Blanco County" ),
	( "Bland County", "Bland County" ),
	( "Bleckley County", "Bleckley County" ),
	( "Bledsoe County", "Bledsoe County" ),
	( "Blount County", "Blount County" ),
	( "Blue Earth County", "Blue Earth County" ),
	( "Boise County", "Boise County" ),
	( "Bolivar County", "Bolivar County" ),
	( "Bollinger County", "Bollinger County" ),
	( "Bon Homme County", "Bon Homme County" ),
	( "Bond County", "Bond County" ),
	( "Bonner County", "Bonner County" ),
	( "Bonneville County", "Bonneville County" ),
	( "Boone County", "Boone County" ),
	( "Borden County", "Borden County" ),
	( "Bosque County", "Bosque County" ),
	( "Bossier Parish", "Bossier Parish" ),
	( "Botetourt County", "Botetourt County" ),
	( "Bottineau County", "Bottineau County" ),
	( "Boulder County", "Boulder County" ),
	( "Boundary County", "Boundary County" ),
	( "Bourbon County", "Bourbon County" ),
	( "Bowie County", "Bowie County" ),
	( "Bowman County", "Bowman County" ),
	( "Box Butte County", "Box Butte County" ),
	( "Box Elder County", "Box Elder County" ),
	( "Boyd County", "Boyd County" ),
	( "Boyle County", "Boyle County" ),
	( "Bracken County", "Bracken County" ),
	( "Bradford County", "Bradford County" ),
	( "Bradley County", "Bradley County" ),
	( "Branch County", "Branch County" ),
	( "Brantley County", "Brantley County" ),
	( "Braxton County", "Braxton County" ),
	( "Brazoria County", "Brazoria County" ),
	( "Brazos County", "Brazos County" ),
	( "Breathitt County", "Breathitt County" ),
	( "Breckinridge County", "Breckinridge County" ),
	( "Bremer County", "Bremer County" ),
	( "Brevard County", "Brevard County" ),
	( "Brewster County", "Brewster County" ),
	( "Briscoe County", "Briscoe County" ),
	( "Bristol Bay Borough", "Bristol Bay Borough" ),
	( "Bristol County", "Bristol County" ),
	( "Bristol city", "Bristol city" ),
	( "Broadwater County", "Broadwater County" ),
	( "Bronx County", "Bronx County" ),
	( "Brooke County", "Brooke County" ),
	( "Brookings County", "Brookings County" ),
	( "Brooks County", "Brooks County" ),
	( "Broome County", "Broome County" ),
	( "Broomfield County", "Broomfield County" ),
	( "Broward County", "Broward County" ),
	( "Brown County", "Brown County" ),
	( "Brule County", "Brule County" ),
	( "Brunswick County", "Brunswick County" ),
	( "Bryan County", "Bryan County" ),
	( "Buchanan County", "Buchanan County" ),
	( "Buckingham County", "Buckingham County" ),
	( "Bucks County", "Bucks County" ),
	( "Buena Vista County", "Buena Vista County" ),
	( "Buena Vista city", "Buena Vista city" ),
	( "Buffalo County", "Buffalo County" ),
	( "Bullitt County", "Bullitt County" ),
	( "Bulloch County", "Bulloch County" ),
	( "Bullock County", "Bullock County" ),
	( "Buncombe County", "Buncombe County" ),
	( "Bureau County", "Bureau County" ),
	( "Burke County", "Burke County" ),
	( "Burleigh County", "Burleigh County" ),
	( "Burleson County", "Burleson County" ),
	( "Burlington County", "Burlington County" ),
	( "Burnet County", "Burnet County" ),
	( "Burnett County", "Burnett County" ),
	( "Burt County", "Burt County" ),
	( "Butler County", "Butler County" ),
	( "Butte County", "Butte County" ),
	( "Butts County", "Butts County" ),
	( "Cabarrus County", "Cabarrus County" ),
	( "Cabell County", "Cabell County" ),
	( "Cache County", "Cache County" ),
	( "Caddo County", "Caddo County" ),
	( "Caddo Parish", "Caddo Parish" ),
	( "Calaveras County", "Calaveras County" ),
	( "Calcasieu Parish", "Calcasieu Parish" ),
	( "Caldwell County", "Caldwell County" ),
	( "Caldwell Parish", "Caldwell Parish" ),
	( "Caledonia County", "Caledonia County" ),
	( "Calhoun County", "Calhoun County" ),
	( "Callahan County", "Callahan County" ),
	( "Callaway County", "Callaway County" ),
	( "Calloway County", "Calloway County" ),
	( "Calumet County", "Calumet County" ),
	( "Calvert County", "Calvert County" ),
	( "Camas County", "Camas County" ),
	( "Cambria County", "Cambria County" ),
	( "Camden County", "Camden County" ),
	( "Cameron County", "Cameron County" ),
	( "Cameron Parish", "Cameron Parish" ),
	( "Camp County", "Camp County" ),
	( "Campbell County", "Campbell County" ),
	( "Canadian County", "Canadian County" ),
	( "Candler County", "Candler County" ),
	( "Cannon County", "Cannon County" ),
	( "Canyon County", "Canyon County" ),
	( "Cape Girardeau County", "Cape Girardeau County" ),
	( "Cape May County", "Cape May County" ),
	( "Carbon County", "Carbon County" ),
	( "Caribou County", "Caribou County" ),
	( "Carlisle County", "Carlisle County" ),
	( "Carlton County", "Carlton County" ),
	( "Caroline County", "Caroline County" ),
	( "Carroll County", "Carroll County" ),
	( "Carson City", "Carson City" ),
	( "Carson County", "Carson County" ),
	( "Carter County", "Carter County" ),
	( "Carteret County", "Carteret County" ),
	( "Carver County", "Carver County" ),
	( "Cascade County", "Cascade County" ),
	( "Casey County", "Casey County" ),
	( "Cass County", "Cass County" ),
	( "Cassia County", "Cassia County" ),
	( "Castro County", "Castro County" ),
	( "Caswell County", "Caswell County" ),
	( "Catahoula Parish", "Catahoula Parish" ),
	( "Catawba County", "Catawba County" ),
	( "Catoosa County", "Catoosa County" ),
	( "Catron County", "Catron County" ),
	( "Cattaraugus County", "Cattaraugus County" ),
	( "Cavalier County", "Cavalier County" ),
	( "Cayuga County", "Cayuga County" ),
	( "Cecil County", "Cecil County" ),
	( "Cedar County", "Cedar County" ),
	( "Centre County", "Centre County" ),
	( "Cerro Gordo County", "Cerro Gordo County" ),
	( "Chaffee County", "Chaffee County" ),
	( "Chambers County", "Chambers County" ),
	( "Champaign County", "Champaign County" ),
	( "Chariton County", "Chariton County" ),
	( "Charles City County", "Charles City County" ),
	( "Charles County", "Charles County" ),
	( "Charles Mix County", "Charles Mix County" ),
	( "Charleston County", "Charleston County" ),
	( "Charlevoix County", "Charlevoix County" ),
	( "Charlotte County", "Charlotte County" ),
	( "Charlottesville city", "Charlottesville city" ),
	( "Charlton County", "Charlton County" ),
	( "Chase County", "Chase County" ),
	( "Chatham County", "Chatham County" ),
	( "Chattahoochee County", "Chattahoochee County" ),
	( "Chattooga County", "Chattooga County" ),
	( "Chautauqua County", "Chautauqua County" ),
	( "Chaves County", "Chaves County" ),
	( "Cheatham County", "Cheatham County" ),
	( "Cheboygan County", "Cheboygan County" ),
	( "Chelan County", "Chelan County" ),
	( "Chemung County", "Chemung County" ),
	( "Chenango County", "Chenango County" ),
	( "Cherokee County", "Cherokee County" ),
	( "Cherry County", "Cherry County" ),
	( "Chesapeake city", "Chesapeake city" ),
	( "Cheshire County", "Cheshire County" ),
	( "Chester County", "Chester County" ),
	( "Chesterfield County", "Chesterfield County" ),
	( "Cheyenne County", "Cheyenne County" ),
	( "Chickasaw County", "Chickasaw County" ),
	( "Chicot County", "Chicot County" ),
	( "Childress County", "Childress County" ),
	( "Chilton County", "Chilton County" ),
	( "Chippewa County", "Chippewa County" ),
	( "Chisago County", "Chisago County" ),
	( "Chittenden County", "Chittenden County" ),
	( "Choctaw County", "Choctaw County" ),
	( "Chouteau County", "Chouteau County" ),
	( "Chowan County", "Chowan County" ),
	( "Christian County", "Christian County" ),
	( "Chugach Census Area", "Chugach Census Area" ),
	( "Churchill County", "Churchill County" ),
	( "Cibola County", "Cibola County" ),
	( "Cimarron County", "Cimarron County" ),
	( "Citrus County", "Citrus County" ),
	( "Clackamas County", "Clackamas County" ),
	( "Claiborne County", "Claiborne County" ),
	( "Claiborne Parish", "Claiborne Parish" ),
	( "Clallam County", "Clallam County" ),
	( "Clare County", "Clare County" ),
	( "Clarendon County", "Clarendon County" ),
	( "Clarion County", "Clarion County" ),
	( "Clark County", "Clark County" ),
	( "Clarke County", "Clarke County" ),
	( "Clatsop County", "Clatsop County" ),
	( "Clay County", "Clay County" ),
	( "Clayton County", "Clayton County" ),
	( "Clear Creek County", "Clear Creek County" ),
	( "Clearfield County", "Clearfield County" ),
	( "Clearwater County", "Clearwater County" ),
	( "Cleburne County", "Cleburne County" ),
	( "Clermont County", "Clermont County" ),
	( "Cleveland County", "Cleveland County" ),
	( "Clinch County", "Clinch County" ),
	( "Clinton County", "Clinton County" ),
	( "Cloud County", "Cloud County" ),
	( "Coahoma County", "Coahoma County" ),
	( "Coal County", "Coal County" ),
	( "Cobb County", "Cobb County" ),
	( "Cochise County", "Cochise County" ),
	( "Cochran County", "Cochran County" ),
	( "Cocke County", "Cocke County" ),
	( "Coconino County", "Coconino County" ),
	( "Codington County", "Codington County" ),
	( "Coffee County", "Coffee County" ),
	( "Coffey County", "Coffey County" ),
	( "Coke County", "Coke County" ),
	( "Colbert County", "Colbert County" ),
	( "Cole County", "Cole County" ),
	( "Coleman County", "Coleman County" ),
	( "Coles County", "Coles County" ),
	( "Colfax County", "Colfax County" ),
	( "Colleton County", "Colleton County" ),
	( "Collier County", "Collier County" ),
	( "Collin County", "Collin County" ),
	( "Collingsworth County", "Collingsworth County" ),
	( "Colonial Heights city", "Colonial Heights city" ),
	( "Colorado County", "Colorado County" ),
	( "Colquitt County", "Colquitt County" ),
	( "Columbia County", "Columbia County" ),
	( "Columbiana County", "Columbiana County" ),
	( "Columbus County", "Columbus County" ),
	( "Colusa County", "Colusa County" ),
	( "Comal County", "Comal County" ),
	( "Comanche County", "Comanche County" ),
	( "Concho County", "Concho County" ),
	( "Concordia Parish", "Concordia Parish" ),
	( "Conecuh County", "Conecuh County" ),
	( "Conejos County", "Conejos County" ),
	( "Contra Costa County", "Contra Costa County" ),
	( "Converse County", "Converse County" ),
	( "Conway County", "Conway County" ),
	( "Cook County", "Cook County" ),
	( "Cooke County", "Cooke County" ),
	( "Cooper County", "Cooper County" ),
	( "Coos County", "Coos County" ),
	( "Coosa County", "Coosa County" ),
	( "Copiah County", "Copiah County" ),
	( "Copper River Census Area", "Copper River Census Area" ),
	( "Corson County", "Corson County" ),
	( "Cortland County", "Cortland County" ),
	( "Coryell County", "Coryell County" ),
	( "Coshocton County", "Coshocton County" ),
	( "Costilla County", "Costilla County" ),
	( "Cottle County", "Cottle County" ),
	( "Cotton County", "Cotton County" ),
	( "Cottonwood County", "Cottonwood County" ),
	( "Covington County", "Covington County" ),
	( "Covington city", "Covington city" ),
	( "Coweta County", "Coweta County" ),
	( "Cowley County", "Cowley County" ),
	( "Cowlitz County", "Cowlitz County" ),
	( "Craig County", "Craig County" ),
	( "Craighead County", "Craighead County" ),
	( "Crane County", "Crane County" ),
	( "Craven County", "Craven County" ),
	( "Crawford County", "Crawford County" ),
	( "Creek County", "Creek County" ),
	( "Crenshaw County", "Crenshaw County" ),
	( "Crisp County", "Crisp County" ),
	( "Crittenden County", "Crittenden County" ),
	( "Crockett County", "Crockett County" ),
	( "Crook County", "Crook County" ),
	( "Crosby County", "Crosby County" ),
	( "Cross County", "Cross County" ),
	( "Crow Wing County", "Crow Wing County" ),
	( "Crowley County", "Crowley County" ),
	( "Culberson County", "Culberson County" ),
	( "Cullman County", "Cullman County" ),
	( "Culpeper County", "Culpeper County" ),
	( "Cumberland County", "Cumberland County" ),
	( "Cuming County", "Cuming County" ),
	( "Currituck County", "Currituck County" ),
	( "Curry County", "Curry County" ),
	( "Custer County", "Custer County" ),
	( "Cuyahoga County", "Cuyahoga County" ),
	( "Dade County", "Dade County" ),
	( "Daggett County", "Daggett County" ),
	( "Dakota County", "Dakota County" ),
	( "Dale County", "Dale County" ),
	( "Dallam County", "Dallam County" ),
	( "Dallas County", "Dallas County" ),
	( "Dane County", "Dane County" ),
	( "Daniels County", "Daniels County" ),
	( "Danville city", "Danville city" ),
	( "Dare County", "Dare County" ),
	( "Darke County", "Darke County" ),
	( "Darlington County", "Darlington County" ),
	( "Dauphin County", "Dauphin County" ),
	( "Davidson County", "Davidson County" ),
	( "Davie County", "Davie County" ),
	( "Daviess County", "Daviess County" ),
	( "Davis County", "Davis County" ),
	( "Davison County", "Davison County" ),
	( "Dawes County", "Dawes County" ),
	( "Dawson County", "Dawson County" ),
	( "Day County", "Day County" ),
	( "De Baca County", "De Baca County" ),
	( "De Soto Parish", "De Soto Parish" ),
	( "De Witt County", "De Witt County" ),
	( "DeKalb County", "DeKalb County" ),
	( "DeSoto County", "DeSoto County" ),
	( "DeWitt County", "DeWitt County" ),
	( "Deaf Smith County", "Deaf Smith County" ),
	( "Dearborn County", "Dearborn County" ),
	( "Decatur County", "Decatur County" ),
	( "Deer Lodge County", "Deer Lodge County" ),
	( "Defiance County", "Defiance County" ),
	( "Del Norte County", "Del Norte County" ),
	( "Delaware County", "Delaware County" ),
	( "Delta County", "Delta County" ),
	( "Denali Borough", "Denali Borough" ),
	( "Dent County", "Dent County" ),
	( "Denton County", "Denton County" ),
	( "Denver County", "Denver County" ),
	( "Des Moines County", "Des Moines County" ),
	( "Deschutes County", "Deschutes County" ),
	( "Desha County", "Desha County" ),
	( "Deuel County", "Deuel County" ),
	( "Dewey County", "Dewey County" ),
	( "Dickens County", "Dickens County" ),
	( "Dickenson County", "Dickenson County" ),
	( "Dickey County", "Dickey County" ),
	( "Dickinson County", "Dickinson County" ),
	( "Dickson County", "Dickson County" ),
	( "Dillingham Census Area", "Dillingham Census Area" ),
	( "Dillon County", "Dillon County" ),
	( "Dimmit County", "Dimmit County" ),
	( "Dinwiddie County", "Dinwiddie County" ),
	( "District of Columbia", "District of Columbia" ),
	( "Divide County", "Divide County" ),
	( "Dixie County", "Dixie County" ),
	( "Dixon County", "Dixon County" ),
	( "Doddridge County", "Doddridge County" ),
	( "Dodge County", "Dodge County" ),
	( "Dolores County", "Dolores County" ),
	( "Doniphan County", "Doniphan County" ),
	( "Donley County", "Donley County" ),
	( "Dooly County", "Dooly County" ),
	( "Door County", "Door County" ),
	( "Dorchester County", "Dorchester County" ),
	( "Dougherty County", "Dougherty County" ),
	( "Douglas County", "Douglas County" ),
	( "Do�a Ana County", "Do�a Ana County" ),
	( "Drew County", "Drew County" ),
	( "DuPage County", "DuPage County" ),
	( "Dubois County", "Dubois County" ),
	( "Dubuque County", "Dubuque County" ),
	( "Duchesne County", "Duchesne County" ),
	( "Dukes County", "Dukes County" ),
	( "Dundy County", "Dundy County" ),
	( "Dunklin County", "Dunklin County" ),
	( "Dunn County", "Dunn County" ),
	( "Duplin County", "Duplin County" ),
	( "Durham County", "Durham County" ),
	( "Dutchess County", "Dutchess County" ),
	( "Duval County", "Duval County" ),
	( "Dyer County", "Dyer County" ),
	( "Eagle County", "Eagle County" ),
	( "Early County", "Early County" ),
	( "East Baton Rouge Parish", "East Baton Rouge Parish" ),
	( "East Carroll Parish", "East Carroll Parish" ),
	( "East Feliciana Parish", "East Feliciana Parish" ),
	( "Eastland County", "Eastland County" ),
	( "Eaton County", "Eaton County" ),
	( "Eau Claire County", "Eau Claire County" ),
	( "Echols County", "Echols County" ),
	( "Ector County", "Ector County" ),
	( "Eddy County", "Eddy County" ),
	( "Edgar County", "Edgar County" ),
	( "Edgecombe County", "Edgecombe County" ),
	( "Edgefield County", "Edgefield County" ),
	( "Edmonson County", "Edmonson County" ),
	( "Edmunds County", "Edmunds County" ),
	( "Edwards County", "Edwards County" ),
	( "Effingham County", "Effingham County" ),
	( "El Dorado County", "El Dorado County" ),
	( "El Paso County", "El Paso County" ),
	( "Elbert County", "Elbert County" ),
	( "Elk County", "Elk County" ),
	( "Elkhart County", "Elkhart County" ),
	( "Elko County", "Elko County" ),
	( "Elliott County", "Elliott County" ),
	( "Ellis County", "Ellis County" ),
	( "Ellsworth County", "Ellsworth County" ),
	( "Elmore County", "Elmore County" ),
	( "Emanuel County", "Emanuel County" ),
	( "Emery County", "Emery County" ),
	( "Emmet County", "Emmet County" ),
	( "Emmons County", "Emmons County" ),
	( "Emporia city", "Emporia city" ),
	( "Erath County", "Erath County" ),
	( "Erie County", "Erie County" ),
	( "Escambia County", "Escambia County" ),
	( "Esmeralda County", "Esmeralda County" ),
	( "Essex County", "Essex County" ),
	( "Estill County", "Estill County" ),
	( "Etowah County", "Etowah County" ),
	( "Eureka County", "Eureka County" ),
	( "Evangeline Parish", "Evangeline Parish" ),
	( "Evans County", "Evans County" ),
	( "Fairbanks North Star Borough", "Fairbanks North Star Borough" ),
	( "Fairfax County", "Fairfax County" ),
	( "Fairfax city", "Fairfax city" ),
	( "Fairfield County", "Fairfield County" ),
	( "Fall River County", "Fall River County" ),
	( "Fallon County", "Fallon County" ),
	( "Falls Church city", "Falls Church city" ),
	( "Falls County", "Falls County" ),
	( "Fannin County", "Fannin County" ),
	( "Faribault County", "Faribault County" ),
	( "Faulk County", "Faulk County" ),
	( "Faulkner County", "Faulkner County" ),
	( "Fauquier County", "Fauquier County" ),
	( "Fayette County", "Fayette County" ),
	( "Fentress County", "Fentress County" ),
	( "Fergus County", "Fergus County" ),
	( "Ferry County", "Ferry County" ),
	( "Fillmore County", "Fillmore County" ),
	( "Finney County", "Finney County" ),
	( "Fisher County", "Fisher County" ),
	( "Flagler County", "Flagler County" ),
	( "Flathead County", "Flathead County" ),
	( "Fleming County", "Fleming County" ),
	( "Florence County", "Florence County" ),
	( "Floyd County", "Floyd County" ),
	( "Fluvanna County", "Fluvanna County" ),
	( "Foard County", "Foard County" ),
	( "Fond du Lac County", "Fond du Lac County" ),
	( "Ford County", "Ford County" ),
	( "Forest County", "Forest County" ),
	( "Forrest County", "Forrest County" ),
	( "Forsyth County", "Forsyth County" ),
	( "Fort Bend County", "Fort Bend County" ),
	( "Foster County", "Foster County" ),
	( "Fountain County", "Fountain County" ),
	( "Franklin County", "Franklin County" ),
	( "Franklin Parish", "Franklin Parish" ),
	( "Franklin city", "Franklin city" ),
	( "Frederick County", "Frederick County" ),
	( "Fredericksburg city", "Fredericksburg city" ),
	( "Freeborn County", "Freeborn County" ),
	( "Freestone County", "Freestone County" ),
	( "Fremont County", "Fremont County" ),
	( "Fresno County", "Fresno County" ),
	( "Frio County", "Frio County" ),
	( "Frontier County", "Frontier County" ),
	( "Fulton County", "Fulton County" ),
	( "Furnas County", "Furnas County" ),
	( "Gadsden County", "Gadsden County" ),
	( "Gage County", "Gage County" ),
	( "Gaines County", "Gaines County" ),
	( "Galax city", "Galax city" ),
	( "Gallatin County", "Gallatin County" ),
	( "Gallia County", "Gallia County" ),
	( "Galveston County", "Galveston County" ),
	( "Garden County", "Garden County" ),
	( "Garfield County", "Garfield County" ),
	( "Garland County", "Garland County" ),
	( "Garrard County", "Garrard County" ),
	( "Garrett County", "Garrett County" ),
	( "Garvin County", "Garvin County" ),
	( "Garza County", "Garza County" ),
	( "Gasconade County", "Gasconade County" ),
	( "Gaston County", "Gaston County" ),
	( "Gates County", "Gates County" ),
	( "Geary County", "Geary County" ),
	( "Geauga County", "Geauga County" ),
	( "Gem County", "Gem County" ),
	( "Genesee County", "Genesee County" ),
	( "Geneva County", "Geneva County" ),
	( "Gentry County", "Gentry County" ),
	( "George County", "George County" ),
	( "Georgetown County", "Georgetown County" ),
	( "Gibson County", "Gibson County" ),
	( "Gila County", "Gila County" ),
	( "Gilchrist County", "Gilchrist County" ),
	( "Giles County", "Giles County" ),
	( "Gillespie County", "Gillespie County" ),
	( "Gilliam County", "Gilliam County" ),
	( "Gilmer County", "Gilmer County" ),
	( "Gilpin County", "Gilpin County" ),
	( "Glacier County", "Glacier County" ),
	( "Glades County", "Glades County" ),
	( "Gladwin County", "Gladwin County" ),
	( "Glascock County", "Glascock County" ),
	( "Glasscock County", "Glasscock County" ),
	( "Glenn County", "Glenn County" ),
	( "Gloucester County", "Gloucester County" ),
	( "Glynn County", "Glynn County" ),
	( "Gogebic County", "Gogebic County" ),
	( "Golden Valley County", "Golden Valley County" ),
	( "Goliad County", "Goliad County" ),
	( "Gonzales County", "Gonzales County" ),
	( "Goochland County", "Goochland County" ),
	( "Goodhue County", "Goodhue County" ),
	( "Gooding County", "Gooding County" ),
	( "Gordon County", "Gordon County" ),
	( "Goshen County", "Goshen County" ),
	( "Gosper County", "Gosper County" ),
	( "Gove County", "Gove County" ),
	( "Grady County", "Grady County" ),
	( "Grafton County", "Grafton County" ),
	( "Graham County", "Graham County" ),
	( "Grainger County", "Grainger County" ),
	( "Grand County", "Grand County" ),
	( "Grand Forks County", "Grand Forks County" ),
	( "Grand Isle County", "Grand Isle County" ),
	( "Grand Traverse County", "Grand Traverse County" ),
	( "Granite County", "Granite County" ),
	( "Grant County", "Grant County" ),
	( "Grant Parish", "Grant Parish" ),
	( "Granville County", "Granville County" ),
	( "Gratiot County", "Gratiot County" ),
	( "Graves County", "Graves County" ),
	( "Gray County", "Gray County" ),
	( "Grays Harbor County", "Grays Harbor County" ),
	( "Grayson County", "Grayson County" ),
	( "Greeley County", "Greeley County" ),
	( "Green County", "Green County" ),
	( "Green Lake County", "Green Lake County" ),
	( "Greenbrier County", "Greenbrier County" ),
	( "Greene County", "Greene County" ),
	( "Greenlee County", "Greenlee County" ),
	( "Greensville County", "Greensville County" ),
	( "Greenup County", "Greenup County" ),
	( "Greenville County", "Greenville County" ),
	( "Greenwood County", "Greenwood County" ),
	( "Greer County", "Greer County" ),
	( "Gregg County", "Gregg County" ),
	( "Gregory County", "Gregory County" ),
	( "Grenada County", "Grenada County" ),
	( "Griggs County", "Griggs County" ),
	( "Grimes County", "Grimes County" ),
	( "Grundy County", "Grundy County" ),
	( "Guadalupe County", "Guadalupe County" ),
	( "Guernsey County", "Guernsey County" ),
	( "Guilford County", "Guilford County" ),
	( "Gulf County", "Gulf County" ),
	( "Gunnison County", "Gunnison County" ),
	( "Guthrie County", "Guthrie County" ),
	( "Gwinnett County", "Gwinnett County" ),
	( "Haakon County", "Haakon County" ),
	( "Habersham County", "Habersham County" ),
	( "Haines Borough", "Haines Borough" ),
	( "Hale County", "Hale County" ),
	( "Halifax County", "Halifax County" ),
	( "Hall County", "Hall County" ),
	( "Hamblen County", "Hamblen County" ),
	( "Hamilton County", "Hamilton County" ),
	( "Hamlin County", "Hamlin County" ),
	( "Hampden County", "Hampden County" ),
	( "Hampshire County", "Hampshire County" ),
	( "Hampton County", "Hampton County" ),
	( "Hampton city", "Hampton city" ),
	( "Hancock County", "Hancock County" ),
	( "Hand County", "Hand County" ),
	( "Hanover County", "Hanover County" ),
	( "Hansford County", "Hansford County" ),
	( "Hanson County", "Hanson County" ),
	( "Haralson County", "Haralson County" ),
	( "Hardee County", "Hardee County" ),
	( "Hardeman County", "Hardeman County" ),
	( "Hardin County", "Hardin County" ),
	( "Harding County", "Harding County" ),
	( "Hardy County", "Hardy County" ),
	( "Harford County", "Harford County" ),
	( "Harlan County", "Harlan County" ),
	( "Harmon County", "Harmon County" ),
	( "Harnett County", "Harnett County" ),
	( "Harney County", "Harney County" ),
	( "Harper County", "Harper County" ),
	( "Harris County", "Harris County" ),
	( "Harrison County", "Harrison County" ),
	( "Harrisonburg city", "Harrisonburg city" ),
	( "Hart County", "Hart County" ),
	( "Hartford County", "Hartford County" ),
	( "Hartley County", "Hartley County" ),
	( "Harvey County", "Harvey County" ),
	( "Haskell County", "Haskell County" ),
	( "Hawaii County", "Hawaii County" ),
	( "Hawkins County", "Hawkins County" ),
	( "Hayes County", "Hayes County" ),
	( "Hays County", "Hays County" ),
	( "Haywood County", "Haywood County" ),
	( "Heard County", "Heard County" ),
	( "Hemphill County", "Hemphill County" ),
	( "Hempstead County", "Hempstead County" ),
	( "Henderson County", "Henderson County" ),
	( "Hendricks County", "Hendricks County" ),
	( "Hendry County", "Hendry County" ),
	( "Hennepin County", "Hennepin County" ),
	( "Henrico County", "Henrico County" ),
	( "Henry County", "Henry County" ),
	( "Herkimer County", "Herkimer County" ),
	( "Hernando County", "Hernando County" ),
	( "Hertford County", "Hertford County" ),
	( "Hettinger County", "Hettinger County" ),
	( "Hickman County", "Hickman County" ),
	( "Hickory County", "Hickory County" ),
	( "Hidalgo County", "Hidalgo County" ),
	( "Highland County", "Highland County" ),
	( "Highlands County", "Highlands County" ),
	( "Hill County", "Hill County" ),
	( "Hillsborough County", "Hillsborough County" ),
	( "Hillsdale County", "Hillsdale County" ),
	( "Hinds County", "Hinds County" ),
	( "Hinsdale County", "Hinsdale County" ),
	( "Hitchcock County", "Hitchcock County" ),
	( "Hocking County", "Hocking County" ),
	( "Hockley County", "Hockley County" ),
	( "Hodgeman County", "Hodgeman County" ),
	( "Hoke County", "Hoke County" ),
	( "Holmes County", "Holmes County" ),
	( "Holt County", "Holt County" ),
	( "Honolulu County", "Honolulu County" ),
	( "Hood County", "Hood County" ),
	( "Hood River County", "Hood River County" ),
	( "Hooker County", "Hooker County" ),
	( "Hoonah-Angoon Census Area", "Hoonah-Angoon Census Area" ),
	( "Hopewell city", "Hopewell city" ),
	( "Hopkins County", "Hopkins County" ),
	( "Horry County", "Horry County" ),
	( "Hot Spring County", "Hot Spring County" ),
	( "Hot Springs County", "Hot Springs County" ),
	( "Houghton County", "Houghton County" ),
	( "Houston County", "Houston County" ),
	( "Howard County", "Howard County" ),
	( "Howell County", "Howell County" ),
	( "Hubbard County", "Hubbard County" ),
	( "Hudson County", "Hudson County" ),
	( "Hudspeth County", "Hudspeth County" ),
	( "Huerfano County", "Huerfano County" ),
	( "Hughes County", "Hughes County" ),
	( "Humboldt County", "Humboldt County" ),
	( "Humphreys County", "Humphreys County" ),
	( "Hunt County", "Hunt County" ),
	( "Hunterdon County", "Hunterdon County" ),
	( "Huntingdon County", "Huntingdon County" ),
	( "Huntington County", "Huntington County" ),
	( "Huron County", "Huron County" ),
	( "Hutchinson County", "Hutchinson County" ),
	( "Hyde County", "Hyde County" ),
	( "Iberia Parish", "Iberia Parish" ),
	( "Iberville Parish", "Iberville Parish" ),
	( "Ida County", "Ida County" ),
	( "Idaho County", "Idaho County" ),
	( "Imperial County", "Imperial County" ),
	( "Independence County", "Independence County" ),
	( "Indian River County", "Indian River County" ),
	( "Indiana County", "Indiana County" ),
	( "Ingham County", "Ingham County" ),
	( "Inyo County", "Inyo County" ),
	( "Ionia County", "Ionia County" ),
	( "Iosco County", "Iosco County" ),
	( "Iowa County", "Iowa County" ),
	( "Iredell County", "Iredell County" ),
	( "Irion County", "Irion County" ),
	( "Iron County", "Iron County" ),
	( "Iroquois County", "Iroquois County" ),
	( "Irwin County", "Irwin County" ),
	( "Isabella County", "Isabella County" ),
	( "Isanti County", "Isanti County" ),
	( "Island County", "Island County" ),
	( "Isle of Wight County", "Isle of Wight County" ),
	( "Issaquena County", "Issaquena County" ),
	( "Itasca County", "Itasca County" ),
	( "Itawamba County", "Itawamba County" ),
	( "Izard County", "Izard County" ),
	( "Jack County", "Jack County" ),
	( "Jackson County", "Jackson County" ),
	( "Jackson Parish", "Jackson Parish" ),
	( "James City County", "James City County" ),
	( "Jasper County", "Jasper County" ),
	( "Jay County", "Jay County" ),
	( "Jeff Davis County", "Jeff Davis County" ),
	( "Jefferson County", "Jefferson County" ),
	( "Jefferson Davis County", "Jefferson Davis County" ),
	( "Jefferson Davis Parish", "Jefferson Davis Parish" ),
	( "Jefferson Parish", "Jefferson Parish" ),
	( "Jenkins County", "Jenkins County" ),
	( "Jennings County", "Jennings County" ),
	( "Jerauld County", "Jerauld County" ),
	( "Jerome County", "Jerome County" ),
	( "Jersey County", "Jersey County" ),
	( "Jessamine County", "Jessamine County" ),
	( "Jewell County", "Jewell County" ),
	( "Jim Hogg County", "Jim Hogg County" ),
	( "Jim Wells County", "Jim Wells County" ),
	( "Jo Daviess County", "Jo Daviess County" ),
	( "Johnson County", "Johnson County" ),
	( "Johnston County", "Johnston County" ),
	( "Jones County", "Jones County" ),
	( "Josephine County", "Josephine County" ),
	( "Juab County", "Juab County" ),
	( "Judith Basin County", "Judith Basin County" ),
	( "Juneau City and Borough", "Juneau City and Borough" ),
	( "Juneau County", "Juneau County" ),
	( "Juniata County", "Juniata County" ),
	( "Kalamazoo County", "Kalamazoo County" ),
	( "Kalawao County", "Kalawao County" ),
	( "Kalkaska County", "Kalkaska County" ),
	( "Kanabec County", "Kanabec County" ),
	( "Kanawha County", "Kanawha County" ),
	( "Kandiyohi County", "Kandiyohi County" ),
	( "Kane County", "Kane County" ),
	( "Kankakee County", "Kankakee County" ),
	( "Karnes County", "Karnes County" ),
	( "Kauai County", "Kauai County" ),
	( "Kaufman County", "Kaufman County" ),
	( "Kay County", "Kay County" ),
	( "Kearney County", "Kearney County" ),
	( "Kearny County", "Kearny County" ),
	( "Keith County", "Keith County" ),
	( "Kemper County", "Kemper County" ),
	( "Kenai Peninsula Borough", "Kenai Peninsula Borough" ),
	( "Kendall County", "Kendall County" ),
	( "Kenedy County", "Kenedy County" ),
	( "Kennebec County", "Kennebec County" ),
	( "Kenosha County", "Kenosha County" ),
	( "Kent County", "Kent County" ),
	( "Kenton County", "Kenton County" ),
	( "Keokuk County", "Keokuk County" ),
	( "Kern County", "Kern County" ),
	( "Kerr County", "Kerr County" ),
	( "Kershaw County", "Kershaw County" ),
	( "Ketchikan Gateway Borough", "Ketchikan Gateway Borough" ),
	( "Kewaunee County", "Kewaunee County" ),
	( "Keweenaw County", "Keweenaw County" ),
	( "Keya Paha County", "Keya Paha County" ),
	( "Kidder County", "Kidder County" ),
	( "Kimball County", "Kimball County" ),
	( "Kimble County", "Kimble County" ),
	( "King County", "King County" ),
	( "King George County", "King George County" ),
	( "King William County", "King William County" ),
	( "King and Queen County", "King and Queen County" ),
	( "Kingfisher County", "Kingfisher County" ),
	( "Kingman County", "Kingman County" ),
	( "Kings County", "Kings County" ),
	( "Kingsbury County", "Kingsbury County" ),
	( "Kinney County", "Kinney County" ),
	( "Kiowa County", "Kiowa County" ),
	( "Kit Carson County", "Kit Carson County" ),
	( "Kitsap County", "Kitsap County" ),
	( "Kittitas County", "Kittitas County" ),
	( "Kittson County", "Kittson County" ),
	( "Klamath County", "Klamath County" ),
	( "Kleberg County", "Kleberg County" ),
	( "Klickitat County", "Klickitat County" ),
	( "Knott County", "Knott County" ),
	( "Knox County", "Knox County" ),
	( "Kodiak Island Borough", "Kodiak Island Borough" ),
	( "Koochiching County", "Koochiching County" ),
	( "Kootenai County", "Kootenai County" ),
	( "Kosciusko County", "Kosciusko County" ),
	( "Kossuth County", "Kossuth County" ),
	( "Kusilvak Census Area", "Kusilvak Census Area" ),
	( "La Crosse County", "La Crosse County" ),
	( "La Paz County", "La Paz County" ),
	( "La Plata County", "La Plata County" ),
	( "La Salle County", "La Salle County" ),
	( "LaGrange County", "LaGrange County" ),
	( "LaMoure County", "LaMoure County" ),
	( "LaPorte County", "LaPorte County" ),
	( "LaSalle County", "LaSalle County" ),
	( "LaSalle Parish", "LaSalle Parish" ),
	( "Labette County", "Labette County" ),
	( "Lac qui Parle County", "Lac qui Parle County" ),
	( "Lackawanna County", "Lackawanna County" ),
	( "Laclede County", "Laclede County" ),
	( "Lafayette County", "Lafayette County" ),
	( "Lafayette Parish", "Lafayette Parish" ),
	( "Lafourche Parish", "Lafourche Parish" ),
	( "Lake County", "Lake County" ),
	( "Lake and Peninsula Borough", "Lake and Peninsula Borough" ),
	( "Lake of the Woods County", "Lake of the Woods County" ),
	( "Lamar County", "Lamar County" ),
	( "Lamb County", "Lamb County" ),
	( "Lamoille County", "Lamoille County" ),
	( "Lampasas County", "Lampasas County" ),
	( "Lancaster County", "Lancaster County" ),
	( "Lander County", "Lander County" ),
	( "Lane County", "Lane County" ),
	( "Langlade County", "Langlade County" ),
	( "Lanier County", "Lanier County" ),
	( "Lapeer County", "Lapeer County" ),
	( "Laramie County", "Laramie County" ),
	( "Larimer County", "Larimer County" ),
	( "Larue County", "Larue County" ),
	( "Las Animas County", "Las Animas County" ),
	( "Lassen County", "Lassen County" ),
	( "Latah County", "Latah County" ),
	( "Latimer County", "Latimer County" ),
	( "Lauderdale County", "Lauderdale County" ),
	( "Laurel County", "Laurel County" ),
	( "Laurens County", "Laurens County" ),
	( "Lavaca County", "Lavaca County" ),
	( "Lawrence County", "Lawrence County" ),
	( "Le Flore County", "Le Flore County" ),
	( "Le Sueur County", "Le Sueur County" ),
	( "Lea County", "Lea County" ),
	( "Leake County", "Leake County" ),
	( "Leavenworth County", "Leavenworth County" ),
	( "Lebanon County", "Lebanon County" ),
	( "Lee County", "Lee County" ),
	( "Leelanau County", "Leelanau County" ),
	( "Leflore County", "Leflore County" ),
	( "Lehigh County", "Lehigh County" ),
	( "Lemhi County", "Lemhi County" ),
	( "Lenawee County", "Lenawee County" ),
	( "Lenoir County", "Lenoir County" ),
	( "Leon County", "Leon County" ),
	( "Leslie County", "Leslie County" ),
	( "Letcher County", "Letcher County" ),
	( "Levy County", "Levy County" ),
	( "Lewis County", "Lewis County" ),
	( "Lewis and Clark County", "Lewis and Clark County" ),
	( "Lexington County", "Lexington County" ),
	( "Lexington city", "Lexington city" ),
	( "Liberty County", "Liberty County" ),
	( "Licking County", "Licking County" ),
	( "Limestone County", "Limestone County" ),
	( "Lincoln County", "Lincoln County" ),
	( "Lincoln Parish", "Lincoln Parish" ),
	( "Linn County", "Linn County" ),
	( "Lipscomb County", "Lipscomb County" ),
	( "Litchfield County", "Litchfield County" ),
	( "Little River County", "Little River County" ),
	( "Live Oak County", "Live Oak County" ),
	( "Livingston County", "Livingston County" ),
	( "Livingston Parish", "Livingston Parish" ),
	( "Llano County", "Llano County" ),
	( "Logan County", "Logan County" ),
	( "Long County", "Long County" ),
	( "Lonoke County", "Lonoke County" ),
	( "Lorain County", "Lorain County" ),
	( "Los Alamos County", "Los Alamos County" ),
	( "Los Angeles County", "Los Angeles County" ),
	( "Loudon County", "Loudon County" ),
	( "Loudoun County", "Loudoun County" ),
	( "Louisa County", "Louisa County" ),
	( "Loup County", "Loup County" ),
	( "Love County", "Love County" ),
	( "Lowndes County", "Lowndes County" ),
	( "Lubbock County", "Lubbock County" ),
	( "Lucas County", "Lucas County" ),
	( "Luce County", "Luce County" ),
	( "Lumpkin County", "Lumpkin County" ),
	( "Luna County", "Luna County" ),
	( "Lunenburg County", "Lunenburg County" ),
	( "Luzerne County", "Luzerne County" ),
	( "Lycoming County", "Lycoming County" ),
	( "Lyman County", "Lyman County" ),
	( "Lynchburg city", "Lynchburg city" ),
	( "Lynn County", "Lynn County" ),
	( "Lyon County", "Lyon County" ),
	( "Mackinac County", "Mackinac County" ),
	( "Macomb County", "Macomb County" ),
	( "Macon County", "Macon County" ),
	( "Macoupin County", "Macoupin County" ),
	( "Madera County", "Madera County" ),
	( "Madison County", "Madison County" ),
	( "Madison Parish", "Madison Parish" ),
	( "Magoffin County", "Magoffin County" ),
	( "Mahaska County", "Mahaska County" ),
	( "Mahnomen County", "Mahnomen County" ),
	( "Mahoning County", "Mahoning County" ),
	( "Major County", "Major County" ),
	( "Malheur County", "Malheur County" ),
	( "Manassas Park city", "Manassas Park city" ),
	( "Manassas city", "Manassas city" ),
	( "Manatee County", "Manatee County" ),
	( "Manistee County", "Manistee County" ),
	( "Manitowoc County", "Manitowoc County" ),
	( "Marathon County", "Marathon County" ),
	( "Marengo County", "Marengo County" ),
	( "Maricopa County", "Maricopa County" ),
	( "Maries County", "Maries County" ),
	( "Marin County", "Marin County" ),
	( "Marinette County", "Marinette County" ),
	( "Marion County", "Marion County" ),
	( "Mariposa County", "Mariposa County" ),
	( "Marlboro County", "Marlboro County" ),
	( "Marquette County", "Marquette County" ),
	( "Marshall County", "Marshall County" ),
	( "Martin County", "Martin County" ),
	( "Martinsville city", "Martinsville city" ),
	( "Mason County", "Mason County" ),
	( "Massac County", "Massac County" ),
	( "Matagorda County", "Matagorda County" ),
	( "Matanuska-Susitna Borough", "Matanuska-Susitna Borough" ),
	( "Mathews County", "Mathews County" ),
	( "Maui County", "Maui County" ),
	( "Maury County", "Maury County" ),
	( "Maverick County", "Maverick County" ),
	( "Mayes County", "Mayes County" ),
	( "McClain County", "McClain County" ),
	( "McCone County", "McCone County" ),
	( "McCook County", "McCook County" ),
	( "McCormick County", "McCormick County" ),
	( "McCracken County", "McCracken County" ),
	( "McCreary County", "McCreary County" ),
	( "McCulloch County", "McCulloch County" ),
	( "McCurtain County", "McCurtain County" ),
	( "McDonald County", "McDonald County" ),
	( "McDonough County", "McDonough County" ),
	( "McDowell County", "McDowell County" ),
	( "McDuffie County", "McDuffie County" ),
	( "McHenry County", "McHenry County" ),
	( "McIntosh County", "McIntosh County" ),
	( "McKean County", "McKean County" ),
	( "McKenzie County", "McKenzie County" ),
	( "McKinley County", "McKinley County" ),
	( "McLean County", "McLean County" ),
	( "McLennan County", "McLennan County" ),
	( "McLeod County", "McLeod County" ),
	( "McMinn County", "McMinn County" ),
	( "McMullen County", "McMullen County" ),
	( "McNairy County", "McNairy County" ),
	( "McPherson County", "McPherson County" ),
	( "Meade County", "Meade County" ),
	( "Meagher County", "Meagher County" ),
	( "Mecklenburg County", "Mecklenburg County" ),
	( "Mecosta County", "Mecosta County" ),
	( "Medina County", "Medina County" ),
	( "Meeker County", "Meeker County" ),
	( "Meigs County", "Meigs County" ),
	( "Mellette County", "Mellette County" ),
	( "Menard County", "Menard County" ),
	( "Mendocino County", "Mendocino County" ),
	( "Menifee County", "Menifee County" ),
	( "Menominee County", "Menominee County" ),
	( "Merced County", "Merced County" ),
	( "Mercer County", "Mercer County" ),
	( "Meriwether County", "Meriwether County" ),
	( "Merrick County", "Merrick County" ),
	( "Merrimack County", "Merrimack County" ),
	( "Mesa County", "Mesa County" ),
	( "Metcalfe County", "Metcalfe County" ),
	( "Miami County", "Miami County" ),
	( "Miami-Dade County", "Miami-Dade County" ),
	( "Middlesex County", "Middlesex County" ),
	( "Midland County", "Midland County" ),
	( "Mifflin County", "Mifflin County" ),
	( "Milam County", "Milam County" ),
	( "Millard County", "Millard County" ),
	( "Mille Lacs County", "Mille Lacs County" ),
	( "Miller County", "Miller County" ),
	( "Mills County", "Mills County" ),
	( "Milwaukee County", "Milwaukee County" ),
	( "Miner County", "Miner County" ),
	( "Mineral County", "Mineral County" ),
	( "Mingo County", "Mingo County" ),
	( "Minidoka County", "Minidoka County" ),
	( "Minnehaha County", "Minnehaha County" ),
	( "Missaukee County", "Missaukee County" ),
	( "Mississippi County", "Mississippi County" ),
	( "Missoula County", "Missoula County" ),
	( "Mitchell County", "Mitchell County" ),
	( "Mobile County", "Mobile County" ),
	( "Modoc County", "Modoc County" ),
	( "Moffat County", "Moffat County" ),
	( "Mohave County", "Mohave County" ),
	( "Moniteau County", "Moniteau County" ),
	( "Monmouth County", "Monmouth County" ),
	( "Mono County", "Mono County" ),
	( "Monona County", "Monona County" ),
	( "Monongalia County", "Monongalia County" ),
	( "Monroe County", "Monroe County" ),
	( "Montague County", "Montague County" ),
	( "Montcalm County", "Montcalm County" ),
	( "Monterey County", "Monterey County" ),
	( "Montezuma County", "Montezuma County" ),
	( "Montgomery County", "Montgomery County" ),
	( "Montmorency County", "Montmorency County" ),
	( "Montour County", "Montour County" ),
	( "Montrose County", "Montrose County" ),
	( "Moody County", "Moody County" ),
	( "Moore County", "Moore County" ),
	( "Mora County", "Mora County" ),
	( "Morehouse Parish", "Morehouse Parish" ),
	( "Morgan County", "Morgan County" ),
	( "Morrill County", "Morrill County" ),
	( "Morris County", "Morris County" ),
	( "Morrison County", "Morrison County" ),
	( "Morrow County", "Morrow County" ),
	( "Morton County", "Morton County" ),
	( "Motley County", "Motley County" ),
	( "Moultrie County", "Moultrie County" ),
	( "Mountrail County", "Mountrail County" ),
	( "Mower County", "Mower County" ),
	( "Muhlenberg County", "Muhlenberg County" ),
	( "Multnomah County", "Multnomah County" ),
	( "Murray County", "Murray County" ),
	( "Muscatine County", "Muscatine County" ),
	( "Muscogee County", "Muscogee County" ),
	( "Muskegon County", "Muskegon County" ),
	( "Muskingum County", "Muskingum County" ),
	( "Muskogee County", "Muskogee County" ),
	( "Musselshell County", "Musselshell County" ),
	( "Nacogdoches County", "Nacogdoches County" ),
	( "Nance County", "Nance County" ),
	( "Nantucket County", "Nantucket County" ),
	( "Napa County", "Napa County" ),
	( "Nash County", "Nash County" ),
	( "Nassau County", "Nassau County" ),
	( "Natchitoches Parish", "Natchitoches Parish" ),
	( "Natrona County", "Natrona County" ),
	( "Navajo County", "Navajo County" ),
	( "Navarro County", "Navarro County" ),
	( "Nelson County", "Nelson County" ),
	( "Nemaha County", "Nemaha County" ),
	( "Neosho County", "Neosho County" ),
	( "Neshoba County", "Neshoba County" ),
	( "Ness County", "Ness County" ),
	( "Nevada County", "Nevada County" ),
	( "New Castle County", "New Castle County" ),
	( "New Hanover County", "New Hanover County" ),
	( "New Haven County", "New Haven County" ),
	( "New Kent County", "New Kent County" ),
	( "New London County", "New London County" ),
	( "New Madrid County", "New Madrid County" ),
	( "New York County", "New York County" ),
	( "Newaygo County", "Newaygo County" ),
	( "Newberry County", "Newberry County" ),
	( "Newport County", "Newport County" ),
	( "Newport News city", "Newport News city" ),
	( "Newton County", "Newton County" ),
	( "Nez Perce County", "Nez Perce County" ),
	( "Niagara County", "Niagara County" ),
	( "Nicholas County", "Nicholas County" ),
	( "Nicollet County", "Nicollet County" ),
	( "Niobrara County", "Niobrara County" ),
	( "Noble County", "Noble County" ),
	( "Nobles County", "Nobles County" ),
	( "Nodaway County", "Nodaway County" ),
	( "Nolan County", "Nolan County" ),
	( "Nome Census Area", "Nome Census Area" ),
	( "Norfolk County", "Norfolk County" ),
	( "Norfolk city", "Norfolk city" ),
	( "Norman County", "Norman County" ),
	( "North Slope Borough", "North Slope Borough" ),
	( "Northampton County", "Northampton County" ),
	( "Northumberland County", "Northumberland County" ),
	( "Northwest Arctic Borough", "Northwest Arctic Borough" ),
	( "Norton County", "Norton County" ),
	( "Norton city", "Norton city" ),
	( "Nottoway County", "Nottoway County" ),
	( "Nowata County", "Nowata County" ),
	( "Noxubee County", "Noxubee County" ),
	( "Nuckolls County", "Nuckolls County" ),
	( "Nueces County", "Nueces County" ),
	( "Nye County", "Nye County" ),
	( "O'Brien County", "O'Brien County" ),
	( "Oakland County", "Oakland County" ),
	( "Obion County", "Obion County" ),
	( "Ocean County", "Ocean County" ),
	( "Oceana County", "Oceana County" ),
	( "Ochiltree County", "Ochiltree County" ),
	( "Oconee County", "Oconee County" ),
	( "Oconto County", "Oconto County" ),
	( "Ogemaw County", "Ogemaw County" ),
	( "Oglala Lakota County", "Oglala Lakota County" ),
	( "Ogle County", "Ogle County" ),
	( "Oglethorpe County", "Oglethorpe County" ),
	( "Ohio County", "Ohio County" ),
	( "Okaloosa County", "Okaloosa County" ),
	( "Okanogan County", "Okanogan County" ),
	( "Okeechobee County", "Okeechobee County" ),
	( "Okfuskee County", "Okfuskee County" ),
	( "Oklahoma County", "Oklahoma County" ),
	( "Okmulgee County", "Okmulgee County" ),
	( "Oktibbeha County", "Oktibbeha County" ),
	( "Oldham County", "Oldham County" ),
	( "Oliver County", "Oliver County" ),
	( "Olmsted County", "Olmsted County" ),
	( "Oneida County", "Oneida County" ),
	( "Onondaga County", "Onondaga County" ),
	( "Onslow County", "Onslow County" ),
	( "Ontario County", "Ontario County" ),
	( "Ontonagon County", "Ontonagon County" ),
	( "Orange County", "Orange County" ),
	( "Orangeburg County", "Orangeburg County" ),
	( "Oregon County", "Oregon County" ),
	( "Orleans County", "Orleans County" ),
	( "Orleans Parish", "Orleans Parish" ),
	( "Osage County", "Osage County" ),
	( "Osborne County", "Osborne County" ),
	( "Osceola County", "Osceola County" ),
	( "Oscoda County", "Oscoda County" ),
	( "Oswego County", "Oswego County" ),
	( "Otero County", "Otero County" ),
	( "Otoe County", "Otoe County" ),
	( "Otsego County", "Otsego County" ),
	( "Ottawa County", "Ottawa County" ),
	( "Otter Tail County", "Otter Tail County" ),
	( "Ouachita County", "Ouachita County" ),
	( "Ouachita Parish", "Ouachita Parish" ),
	( "Ouray County", "Ouray County" ),
	( "Outagamie County", "Outagamie County" ),
	( "Overton County", "Overton County" ),
	( "Owen County", "Owen County" ),
	( "Owsley County", "Owsley County" ),
	( "Owyhee County", "Owyhee County" ),
	( "Oxford County", "Oxford County" ),
	( "Ozark County", "Ozark County" ),
	( "Ozaukee County", "Ozaukee County" ),
	( "Pacific County", "Pacific County" ),
	( "Page County", "Page County" ),
	( "Palm Beach County", "Palm Beach County" ),
	( "Palo Alto County", "Palo Alto County" ),
	( "Palo Pinto County", "Palo Pinto County" ),
	( "Pamlico County", "Pamlico County" ),
	( "Panola County", "Panola County" ),
	( "Park County", "Park County" ),
	( "Parke County", "Parke County" ),
	( "Parker County", "Parker County" ),
	( "Parmer County", "Parmer County" ),
	( "Pasco County", "Pasco County" ),
	( "Pasquotank County", "Pasquotank County" ),
	( "Passaic County", "Passaic County" ),
	( "Patrick County", "Patrick County" ),
	( "Paulding County", "Paulding County" ),
	( "Pawnee County", "Pawnee County" ),
	( "Payette County", "Payette County" ),
	( "Payne County", "Payne County" ),
	( "Peach County", "Peach County" ),
	( "Pearl River County", "Pearl River County" ),
	( "Pecos County", "Pecos County" ),
	( "Pembina County", "Pembina County" ),
	( "Pemiscot County", "Pemiscot County" ),
	( "Pend Oreille County", "Pend Oreille County" ),
	( "Pender County", "Pender County" ),
	( "Pendleton County", "Pendleton County" ),
	( "Pennington County", "Pennington County" ),
	( "Penobscot County", "Penobscot County" ),
	( "Peoria County", "Peoria County" ),
	( "Pepin County", "Pepin County" ),
	( "Perkins County", "Perkins County" ),
	( "Perquimans County", "Perquimans County" ),
	( "Perry County", "Perry County" ),
	( "Pershing County", "Pershing County" ),
	( "Person County", "Person County" ),
	( "Petersburg Borough", "Petersburg Borough" ),
	( "Petersburg city", "Petersburg city" ),
	( "Petroleum County", "Petroleum County" ),
	( "Pettis County", "Pettis County" ),
	( "Phelps County", "Phelps County" ),
	( "Philadelphia County", "Philadelphia County" ),
	( "Phillips County", "Phillips County" ),
	( "Piatt County", "Piatt County" ),
	( "Pickaway County", "Pickaway County" ),
	( "Pickens County", "Pickens County" ),
	( "Pickett County", "Pickett County" ),
	( "Pierce County", "Pierce County" ),
	( "Pike County", "Pike County" ),
	( "Pima County", "Pima County" ),
	( "Pinal County", "Pinal County" ),
	( "Pine County", "Pine County" ),
	( "Pinellas County", "Pinellas County" ),
	( "Pipestone County", "Pipestone County" ),
	( "Piscataquis County", "Piscataquis County" ),
	( "Pitkin County", "Pitkin County" ),
	( "Pitt County", "Pitt County" ),
	( "Pittsburg County", "Pittsburg County" ),
	( "Pittsylvania County", "Pittsylvania County" ),
	( "Piute County", "Piute County" ),
	( "Placer County", "Placer County" ),
	( "Plaquemines Parish", "Plaquemines Parish" ),
	( "Platte County", "Platte County" ),
	( "Pleasants County", "Pleasants County" ),
	( "Plumas County", "Plumas County" ),
	( "Plymouth County", "Plymouth County" ),
	( "Pocahontas County", "Pocahontas County" ),
	( "Poinsett County", "Poinsett County" ),
	( "Pointe Coupee Parish", "Pointe Coupee Parish" ),
	( "Polk County", "Polk County" ),
	( "Pondera County", "Pondera County" ),
	( "Pontotoc County", "Pontotoc County" ),
	( "Pope County", "Pope County" ),
	( "Poquoson city", "Poquoson city" ),
	( "Portage County", "Portage County" ),
	( "Porter County", "Porter County" ),
	( "Portsmouth city", "Portsmouth city" ),
	( "Posey County", "Posey County" ),
	( "Pottawatomie County", "Pottawatomie County" ),
	( "Pottawattamie County", "Pottawattamie County" ),
	( "Potter County", "Potter County" ),
	( "Powder River County", "Powder River County" ),
	( "Powell County", "Powell County" ),
	( "Power County", "Power County" ),
	( "Poweshiek County", "Poweshiek County" ),
	( "Powhatan County", "Powhatan County" ),
	( "Prairie County", "Prairie County" ),
	( "Pratt County", "Pratt County" ),
	( "Preble County", "Preble County" ),
	( "Prentiss County", "Prentiss County" ),
	( "Presidio County", "Presidio County" ),
	( "Presque Isle County", "Presque Isle County" ),
	( "Preston County", "Preston County" ),
	( "Price County", "Price County" ),
	( "Prince Edward County", "Prince Edward County" ),
	( "Prince George County", "Prince George County" ),
	( "Prince George's County", "Prince George's County" ),
	( "Prince William County", "Prince William County" ),
	( "Prince of Wales-Hyder Census Area", "Prince of Wales-Hyder Census Area" ),
	( "Providence County", "Providence County" ),
	( "Prowers County", "Prowers County" ),
	( "Pueblo County", "Pueblo County" ),
	( "Pulaski County", "Pulaski County" ),
	( "Pushmataha County", "Pushmataha County" ),
	( "Putnam County", "Putnam County" ),
	( "Quay County", "Quay County" ),
	( "Queen Anne's County", "Queen Anne's County" ),
	( "Queens County", "Queens County" ),
	( "Quitman County", "Quitman County" ),
	( "Rabun County", "Rabun County" ),
	( "Racine County", "Racine County" ),
	( "Radford city", "Radford city" ),
	( "Rains County", "Rains County" ),
	( "Raleigh County", "Raleigh County" ),
	( "Ralls County", "Ralls County" ),
	( "Ramsey County", "Ramsey County" ),
	( "Randall County", "Randall County" ),
	( "Randolph County", "Randolph County" ),
	( "Rankin County", "Rankin County" ),
	( "Ransom County", "Ransom County" ),
	( "Rapides Parish", "Rapides Parish" ),
	( "Rappahannock County", "Rappahannock County" ),
	( "Ravalli County", "Ravalli County" ),
	( "Rawlins County", "Rawlins County" ),
	( "Ray County", "Ray County" ),
	( "Reagan County", "Reagan County" ),
	( "Real County", "Real County" ),
	( "Red Lake County", "Red Lake County" ),
	( "Red River County", "Red River County" ),
	( "Red River Parish", "Red River Parish" ),
	( "Red Willow County", "Red Willow County" ),
	( "Redwood County", "Redwood County" ),
	( "Reeves County", "Reeves County" ),
	( "Refugio County", "Refugio County" ),
	( "Reno County", "Reno County" ),
	( "Rensselaer County", "Rensselaer County" ),
	( "Renville County", "Renville County" ),
	( "Republic County", "Republic County" ),
	( "Reynolds County", "Reynolds County" ),
	( "Rhea County", "Rhea County" ),
	( "Rice County", "Rice County" ),
	( "Rich County", "Rich County" ),
	( "Richardson County", "Richardson County" ),
	( "Richland County", "Richland County" ),
	( "Richland Parish", "Richland Parish" ),
	( "Richmond County", "Richmond County" ),
	( "Richmond city", "Richmond city" ),
	( "Riley County", "Riley County" ),
	( "Ringgold County", "Ringgold County" ),
	( "Rio Arriba County", "Rio Arriba County" ),
	( "Rio Blanco County", "Rio Blanco County" ),
	( "Rio Grande County", "Rio Grande County" ),
	( "Ripley County", "Ripley County" ),
	( "Ritchie County", "Ritchie County" ),
	( "Riverside County", "Riverside County" ),
	( "Roane County", "Roane County" ),
	( "Roanoke County", "Roanoke County" ),
	( "Roanoke city", "Roanoke city" ),
	( "Roberts County", "Roberts County" ),
	( "Robertson County", "Robertson County" ),
	( "Robeson County", "Robeson County" ),
	( "Rock County", "Rock County" ),
	( "Rock Island County", "Rock Island County" ),
	( "Rockbridge County", "Rockbridge County" ),
	( "Rockcastle County", "Rockcastle County" ),
	( "Rockdale County", "Rockdale County" ),
	( "Rockingham County", "Rockingham County" ),
	( "Rockland County", "Rockland County" ),
	( "Rockwall County", "Rockwall County" ),
	( "Roger Mills County", "Roger Mills County" ),
	( "Rogers County", "Rogers County" ),
	( "Rolette County", "Rolette County" ),
	( "Rooks County", "Rooks County" ),
	( "Roosevelt County", "Roosevelt County" ),
	( "Roscommon County", "Roscommon County" ),
	( "Roseau County", "Roseau County" ),
	( "Rosebud County", "Rosebud County" ),
	( "Ross County", "Ross County" ),
	( "Routt County", "Routt County" ),
	( "Rowan County", "Rowan County" ),
	( "Runnels County", "Runnels County" ),
	( "Rush County", "Rush County" ),
	( "Rusk County", "Rusk County" ),
	( "Russell County", "Russell County" ),
	( "Rutherford County", "Rutherford County" ),
	( "Rutland County", "Rutland County" ),
	( "Sabine County", "Sabine County" ),
	( "Sabine Parish", "Sabine Parish" ),
	( "Sac County", "Sac County" ),
	( "Sacramento County", "Sacramento County" ),
	( "Sagadahoc County", "Sagadahoc County" ),
	( "Saginaw County", "Saginaw County" ),
	( "Saguache County", "Saguache County" ),
	( "Salem County", "Salem County" ),
	( "Salem city", "Salem city" ),
	( "Saline County", "Saline County" ),
	( "Salt Lake County", "Salt Lake County" ),
	( "Saluda County", "Saluda County" ),
	( "Sampson County", "Sampson County" ),
	( "San Augustine County", "San Augustine County" ),
	( "San Benito County", "San Benito County" ),
	( "San Bernardino County", "San Bernardino County" ),
	( "San Diego County", "San Diego County" ),
	( "San Francisco County", "San Francisco County" ),
	( "San Jacinto County", "San Jacinto County" ),
	( "San Joaquin County", "San Joaquin County" ),
	( "San Juan County", "San Juan County" ),
	( "San Luis Obispo County", "San Luis Obispo County" ),
	( "San Mateo County", "San Mateo County" ),
	( "San Miguel County", "San Miguel County" ),
	( "San Patricio County", "San Patricio County" ),
	( "San Saba County", "San Saba County" ),
	( "Sanborn County", "Sanborn County" ),
	( "Sanders County", "Sanders County" ),
	( "Sandoval County", "Sandoval County" ),
	( "Sandusky County", "Sandusky County" ),
	( "Sangamon County", "Sangamon County" ),
	( "Sanilac County", "Sanilac County" ),
	( "Sanpete County", "Sanpete County" ),
	( "Santa Barbara County", "Santa Barbara County" ),
	( "Santa Clara County", "Santa Clara County" ),
	( "Santa Cruz County", "Santa Cruz County" ),
	( "Santa Fe County", "Santa Fe County" ),
	( "Santa Rosa County", "Santa Rosa County" ),
	( "Sarasota County", "Sarasota County" ),
	( "Saratoga County", "Saratoga County" ),
	( "Sargent County", "Sargent County" ),
	( "Sarpy County", "Sarpy County" ),
	( "Sauk County", "Sauk County" ),
	( "Saunders County", "Saunders County" ),
	( "Sawyer County", "Sawyer County" ),
	( "Schenectady County", "Schenectady County" ),
	( "Schleicher County", "Schleicher County" ),
	( "Schley County", "Schley County" ),
	( "Schoharie County", "Schoharie County" ),
	( "Schoolcraft County", "Schoolcraft County" ),
	( "Schuyler County", "Schuyler County" ),
	( "Schuylkill County", "Schuylkill County" ),
	( "Scioto County", "Scioto County" ),
	( "Scotland County", "Scotland County" ),
	( "Scott County", "Scott County" ),
	( "Scotts Bluff County", "Scotts Bluff County" ),
	( "Screven County", "Screven County" ),
	( "Scurry County", "Scurry County" ),
	( "Searcy County", "Searcy County" ),
	( "Sebastian County", "Sebastian County" ),
	( "Sedgwick County", "Sedgwick County" ),
	( "Seminole County", "Seminole County" ),
	( "Seneca County", "Seneca County" ),
	( "Sequatchie County", "Sequatchie County" ),
	( "Sequoyah County", "Sequoyah County" ),
	( "Sevier County", "Sevier County" ),
	( "Seward County", "Seward County" ),
	( "Shackelford County", "Shackelford County" ),
	( "Shannon County", "Shannon County" ),
	( "Sharkey County", "Sharkey County" ),
	( "Sharp County", "Sharp County" ),
	( "Shasta County", "Shasta County" ),
	( "Shawano County", "Shawano County" ),
	( "Shawnee County", "Shawnee County" ),
	( "Sheboygan County", "Sheboygan County" ),
	( "Shelby County", "Shelby County" ),
	( "Shenandoah County", "Shenandoah County" ),
	( "Sherburne County", "Sherburne County" ),
	( "Sheridan County", "Sheridan County" ),
	( "Sherman County", "Sherman County" ),
	( "Shiawassee County", "Shiawassee County" ),
	( "Shoshone County", "Shoshone County" ),
	( "Sibley County", "Sibley County" ),
	( "Sierra County", "Sierra County" ),
	( "Silver Bow County", "Silver Bow County" ),
	( "Simpson County", "Simpson County" ),
	( "Sioux County", "Sioux County" ),
	( "Siskiyou County", "Siskiyou County" ),
	( "Sitka City and Borough", "Sitka City and Borough" ),
	( "Skagit County", "Skagit County" ),
	( "Skagway Municipality", "Skagway Municipality" ),
	( "Skamania County", "Skamania County" ),
	( "Slope County", "Slope County" ),
	( "Smith County", "Smith County" ),
	( "Smyth County", "Smyth County" ),
	( "Snohomish County", "Snohomish County" ),
	( "Snyder County", "Snyder County" ),
	( "Socorro County", "Socorro County" ),
	( "Solano County", "Solano County" ),
	( "Somerset County", "Somerset County" ),
	( "Somervell County", "Somervell County" ),
	( "Sonoma County", "Sonoma County" ),
	( "Southampton County", "Southampton County" ),
	( "Southeast Fairbanks Census Area", "Southeast Fairbanks Census Area" ),
	( "Spalding County", "Spalding County" ),
	( "Spartanburg County", "Spartanburg County" ),
	( "Spencer County", "Spencer County" ),
	( "Spink County", "Spink County" ),
	( "Spokane County", "Spokane County" ),
	( "Spotsylvania County", "Spotsylvania County" ),
	( "St. Bernard Parish", "St. Bernard Parish" ),
	( "St. Charles County", "St. Charles County" ),
	( "St. Charles Parish", "St. Charles Parish" ),
	( "St. Clair County", "St. Clair County" ),
	( "St. Croix County", "St. Croix County" ),
	( "St. Francis County", "St. Francis County" ),
	( "St. Francois County", "St. Francois County" ),
	( "St. Helena Parish", "St. Helena Parish" ),
	( "St. James Parish", "St. James Parish" ),
	( "St. John the Baptist Parish", "St. John the Baptist Parish" ),
	( "St. Johns County", "St. Johns County" ),
	( "St. Joseph County", "St. Joseph County" ),
	( "St. Landry Parish", "St. Landry Parish" ),
	( "St. Lawrence County", "St. Lawrence County" ),
	( "St. Louis County", "St. Louis County" ),
	( "St. Louis city", "St. Louis city" ),
	( "St. Lucie County", "St. Lucie County" ),
	( "St. Martin Parish", "St. Martin Parish" ),
	( "St. Mary Parish", "St. Mary Parish" ),
	( "St. Mary's County", "St. Mary's County" ),
	( "St. Tammany Parish", "St. Tammany Parish" ),
	( "Stafford County", "Stafford County" ),
	( "Stanislaus County", "Stanislaus County" ),
	( "Stanley County", "Stanley County" ),
	( "Stanly County", "Stanly County" ),
	( "Stanton County", "Stanton County" ),
	( "Stark County", "Stark County" ),
	( "Starke County", "Starke County" ),
	( "Starr County", "Starr County" ),
	( "Staunton city", "Staunton city" ),
	( "Ste. Genevieve County", "Ste. Genevieve County" ),
	( "Stearns County", "Stearns County" ),
	( "Steele County", "Steele County" ),
	( "Stephens County", "Stephens County" ),
	( "Stephenson County", "Stephenson County" ),
	( "Sterling County", "Sterling County" ),
	( "Steuben County", "Steuben County" ),
	( "Stevens County", "Stevens County" ),
	( "Stewart County", "Stewart County" ),
	( "Stillwater County", "Stillwater County" ),
	( "Stoddard County", "Stoddard County" ),
	( "Stokes County", "Stokes County" ),
	( "Stone County", "Stone County" ),
	( "Stonewall County", "Stonewall County" ),
	( "Storey County", "Storey County" ),
	( "Story County", "Story County" ),
	( "Strafford County", "Strafford County" ),
	( "Stutsman County", "Stutsman County" ),
	( "Sublette County", "Sublette County" ),
	( "Suffolk County", "Suffolk County" ),
	( "Suffolk city", "Suffolk city" ),
	( "Sullivan County", "Sullivan County" ),
	( "Sully County", "Sully County" ),
	( "Summers County", "Summers County" ),
	( "Summit County", "Summit County" ),
	( "Sumner County", "Sumner County" ),
	( "Sumter County", "Sumter County" ),
	( "Sunflower County", "Sunflower County" ),
	( "Surry County", "Surry County" ),
	( "Susquehanna County", "Susquehanna County" ),
	( "Sussex County", "Sussex County" ),
	( "Sutter County", "Sutter County" ),
	( "Sutton County", "Sutton County" ),
	( "Suwannee County", "Suwannee County" ),
	( "Swain County", "Swain County" ),
	( "Sweet Grass County", "Sweet Grass County" ),
	( "Sweetwater County", "Sweetwater County" ),
	( "Swift County", "Swift County" ),
	( "Swisher County", "Swisher County" ),
	( "Switzerland County", "Switzerland County" ),
	( "Talbot County", "Talbot County" ),
	( "Taliaferro County", "Taliaferro County" ),
	( "Talladega County", "Talladega County" ),
	( "Tallahatchie County", "Tallahatchie County" ),
	( "Tallapoosa County", "Tallapoosa County" ),
	( "Tama County", "Tama County" ),
	( "Taney County", "Taney County" ),
	( "Tangipahoa Parish", "Tangipahoa Parish" ),
	( "Taos County", "Taos County" ),
	( "Tarrant County", "Tarrant County" ),
	( "Tate County", "Tate County" ),
	( "Tattnall County", "Tattnall County" ),
	( "Taylor County", "Taylor County" ),
	( "Tazewell County", "Tazewell County" ),
	( "Tehama County", "Tehama County" ),
	( "Telfair County", "Telfair County" ),
	( "Teller County", "Teller County" ),
	( "Tensas Parish", "Tensas Parish" ),
	( "Terrebonne Parish", "Terrebonne Parish" ),
	( "Terrell County", "Terrell County" ),
	( "Terry County", "Terry County" ),
	( "Teton County", "Teton County" ),
	( "Texas County", "Texas County" ),
	( "Thayer County", "Thayer County" ),
	( "Thomas County", "Thomas County" ),
	( "Throckmorton County", "Throckmorton County" ),
	( "Thurston County", "Thurston County" ),
	( "Tift County", "Tift County" ),
	( "Tillamook County", "Tillamook County" ),
	( "Tillman County", "Tillman County" ),
	( "Tioga County", "Tioga County" ),
	( "Tippah County", "Tippah County" ),
	( "Tippecanoe County", "Tippecanoe County" ),
	( "Tipton County", "Tipton County" ),
	( "Tishomingo County", "Tishomingo County" ),
	( "Titus County", "Titus County" ),
	( "Todd County", "Todd County" ),
	( "Tolland County", "Tolland County" ),
	( "Tom Green County", "Tom Green County" ),
	( "Tompkins County", "Tompkins County" ),
	( "Tooele County", "Tooele County" ),
	( "Toole County", "Toole County" ),
	( "Toombs County", "Toombs County" ),
	( "Torrance County", "Torrance County" ),
	( "Towner County", "Towner County" ),
	( "Towns County", "Towns County" ),
	( "Traill County", "Traill County" ),
	( "Transylvania County", "Transylvania County" ),
	( "Traverse County", "Traverse County" ),
	( "Travis County", "Travis County" ),
	( "Treasure County", "Treasure County" ),
	( "Trego County", "Trego County" ),
	( "Trempealeau County", "Trempealeau County" ),
	( "Treutlen County", "Treutlen County" ),
	( "Trigg County", "Trigg County" ),
	( "Trimble County", "Trimble County" ),
	( "Trinity County", "Trinity County" ),
	( "Tripp County", "Tripp County" ),
	( "Troup County", "Troup County" ),
	( "Trousdale County", "Trousdale County" ),
	( "Trumbull County", "Trumbull County" ),
	( "Tucker County", "Tucker County" ),
	( "Tulare County", "Tulare County" ),
	( "Tulsa County", "Tulsa County" ),
	( "Tunica County", "Tunica County" ),
	( "Tuolumne County", "Tuolumne County" ),
	( "Turner County", "Turner County" ),
	( "Tuscaloosa County", "Tuscaloosa County" ),
	( "Tuscarawas County", "Tuscarawas County" ),
	( "Tuscola County", "Tuscola County" ),
	( "Twiggs County", "Twiggs County" ),
	( "Twin Falls County", "Twin Falls County" ),
	( "Tyler County", "Tyler County" ),
	( "Tyrrell County", "Tyrrell County" ),
	( "Uinta County", "Uinta County" ),
	( "Uintah County", "Uintah County" ),
	( "Ulster County", "Ulster County" ),
	( "Umatilla County", "Umatilla County" ),
	( "Unicoi County", "Unicoi County" ),
	( "Union County", "Union County" ),
	( "Union Parish", "Union Parish" ),
	( "Upshur County", "Upshur County" ),
	( "Upson County", "Upson County" ),
	( "Upton County", "Upton County" ),
	( "Utah County", "Utah County" ),
	( "Uvalde County", "Uvalde County" ),
	( "Val Verde County", "Val Verde County" ),
	( "Valencia County", "Valencia County" ),
	( "Valley County", "Valley County" ),
	( "Van Buren County", "Van Buren County" ),
	( "Van Wert County", "Van Wert County" ),
	( "Van Zandt County", "Van Zandt County" ),
	( "Vance County", "Vance County" ),
	( "Vanderburgh County", "Vanderburgh County" ),
	( "Venango County", "Venango County" ),
	( "Ventura County", "Ventura County" ),
	( "Vermilion County", "Vermilion County" ),
	( "Vermilion Parish", "Vermilion Parish" ),
	( "Vermillion County", "Vermillion County" ),
	( "Vernon County", "Vernon County" ),
	( "Vernon Parish", "Vernon Parish" ),
	( "Victoria County", "Victoria County" ),
	( "Vigo County", "Vigo County" ),
	( "Vilas County", "Vilas County" ),
	( "Vinton County", "Vinton County" ),
	( "Virginia Beach city", "Virginia Beach city" ),
	( "Volusia County", "Volusia County" ),
	( "Wabash County", "Wabash County" ),
	( "Wabasha County", "Wabasha County" ),
	( "Wabaunsee County", "Wabaunsee County" ),
	( "Wadena County", "Wadena County" ),
	( "Wagoner County", "Wagoner County" ),
	( "Wahkiakum County", "Wahkiakum County" ),
	( "Wake County", "Wake County" ),
	( "Wakulla County", "Wakulla County" ),
	( "Waldo County", "Waldo County" ),
	( "Walker County", "Walker County" ),
	( "Walla Walla County", "Walla Walla County" ),
	( "Wallace County", "Wallace County" ),
	( "Waller County", "Waller County" ),
	( "Wallowa County", "Wallowa County" ),
	( "Walsh County", "Walsh County" ),
	( "Walthall County", "Walthall County" ),
	( "Walton County", "Walton County" ),
	( "Walworth County", "Walworth County" ),
	( "Wapello County", "Wapello County" ),
	( "Ward County", "Ward County" ),
	( "Ware County", "Ware County" ),
	( "Warren County", "Warren County" ),
	( "Warrick County", "Warrick County" ),
	( "Wasatch County", "Wasatch County" ),
	( "Wasco County", "Wasco County" ),
	( "Waseca County", "Waseca County" ),
	( "Washakie County", "Washakie County" ),
	( "Washburn County", "Washburn County" ),
	( "Washington County", "Washington County" ),
	( "Washington Parish", "Washington Parish" ),
	( "Washita County", "Washita County" ),
	( "Washoe County", "Washoe County" ),
	( "Washtenaw County", "Washtenaw County" ),
	( "Watauga County", "Watauga County" ),
	( "Watonwan County", "Watonwan County" ),
	( "Waukesha County", "Waukesha County" ),
	( "Waupaca County", "Waupaca County" ),
	( "Waushara County", "Waushara County" ),
	( "Wayne County", "Wayne County" ),
	( "Waynesboro city", "Waynesboro city" ),
	( "Weakley County", "Weakley County" ),
	( "Webb County", "Webb County" ),
	( "Weber County", "Weber County" ),
	( "Webster County", "Webster County" ),
	( "Webster Parish", "Webster Parish" ),
	( "Weld County", "Weld County" ),
	( "Wells County", "Wells County" ),
	( "West Baton Rouge Parish", "West Baton Rouge Parish" ),
	( "West Carroll Parish", "West Carroll Parish" ),
	( "West Feliciana Parish", "West Feliciana Parish" ),
	( "Westchester County", "Westchester County" ),
	( "Westmoreland County", "Westmoreland County" ),
	( "Weston County", "Weston County" ),
	( "Wetzel County", "Wetzel County" ),
	( "Wexford County", "Wexford County" ),
	( "Wharton County", "Wharton County" ),
	( "Whatcom County", "Whatcom County" ),
	( "Wheatland County", "Wheatland County" ),
	( "Wheeler County", "Wheeler County" ),
	( "White County", "White County" ),
	( "White Pine County", "White Pine County" ),
	( "Whiteside County", "Whiteside County" ),
	( "Whitfield County", "Whitfield County" ),
	( "Whitley County", "Whitley County" ),
	( "Whitman County", "Whitman County" ),
	( "Wibaux County", "Wibaux County" ),
	( "Wichita County", "Wichita County" ),
	( "Wicomico County", "Wicomico County" ),
	( "Wilbarger County", "Wilbarger County" ),
	( "Wilcox County", "Wilcox County" ),
	( "Wilkes County", "Wilkes County" ),
	( "Wilkin County", "Wilkin County" ),
	( "Wilkinson County", "Wilkinson County" ),
	( "Will County", "Will County" ),
	( "Willacy County", "Willacy County" ),
	( "Williams County", "Williams County" ),
	( "Williamsburg County", "Williamsburg County" ),
	( "Williamsburg city", "Williamsburg city" ),
	( "Williamson County", "Williamson County" ),
	( "Wilson County", "Wilson County" ),
	( "Winchester city", "Winchester city" ),
	( "Windham County", "Windham County" ),
	( "Windsor County", "Windsor County" ),
	( "Winkler County", "Winkler County" ),
	( "Winn Parish", "Winn Parish" ),
	( "Winnebago County", "Winnebago County" ),
	( "Winneshiek County", "Winneshiek County" ),
	( "Winona County", "Winona County" ),
	( "Winston County", "Winston County" ),
	( "Wirt County", "Wirt County" ),
	( "Wise County", "Wise County" ),
	( "Wolfe County", "Wolfe County" ),
	( "Wood County", "Wood County" ),
	( "Woodbury County", "Woodbury County" ),
	( "Woodford County", "Woodford County" ),
	( "Woodruff County", "Woodruff County" ),
	( "Woods County", "Woods County" ),
	( "Woodson County", "Woodson County" ),
	( "Woodward County", "Woodward County" ),
	( "Worcester County", "Worcester County" ),
	( "Worth County", "Worth County" ),
	( "Wrangell City and Borough", "Wrangell City and Borough" ),
	( "Wright County", "Wright County" ),
	( "Wyandot County", "Wyandot County" ),
	( "Wyandotte County", "Wyandotte County" ),
	( "Wyoming County", "Wyoming County" ),
	( "Wythe County", "Wythe County" ),
	( "Yadkin County", "Yadkin County" ),
	( "Yakima County", "Yakima County" ),
	( "Yakutat City and Borough", "Yakutat City and Borough" ),
	( "Yalobusha County", "Yalobusha County" ),
	( "Yamhill County", "Yamhill County" ),
	( "Yancey County", "Yancey County" ),
	( "Yankton County", "Yankton County" ),
	( "Yates County", "Yates County" ),
	( "Yavapai County", "Yavapai County" ),
	( "Yazoo County", "Yazoo County" ),
	( "Yell County", "Yell County" ),
	( "Yellow Medicine County", "Yellow Medicine County" ),
	( "Yellowstone County", "Yellowstone County" ),
	( "Yoakum County", "Yoakum County" ),
	( "Yolo County", "Yolo County" ),
	( "York County", "York County" ),
	( "Young County", "Young County" ),
	( "Yuba County", "Yuba County" ),
	( "Yukon-Koyukuk Census Area", "Yukon-Koyukuk Census Area" ),
	( "Yuma County", "Yuma County" ),
	( "Zapata County", "Zapata County" ),
	( "Zavala County", "Zavala County" ),
	( "Ziebach County", "Ziebach County" )
)